# in order to use old-style configuration of workflow (before state-machines implementations) please refer to master branch
workflow:
    workflows:
        order_publishing:
            marking_store:
                type: multiple_state
            supports:
                - AppBundle\Entity\Order
            places:
                - draft
                - spellchecked
                - published
            transitions:
                spellcheck:
                    from: draft
                    to:   spellchecked
                publish:
                    from: spellchecked
                    to:   published